import Head from 'next/head'
import Landing from "../components/Landing.js";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ping</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <Landing />
    </div>
  )
}
